// Generated by tools/render-headings.html (see that file). Maps each fixed
// email heading to its pre-drawn Horizon image in assets/headings/.
// Headings not listed here are sent as styled text instead.

export const HEADING_IMAGES: Record<string, { file: string; w: number; h: number }> = {};
export const HEADING_BYTES: Record<string, ArrayBuffer> = {};
